ALTER TABLE users
ADD COLUMN IF NOT EXISTS gender_id INT(11) NULL,
ADD COLUMN IF NOT EXISTS faculty_id INT(11) NULL;

CREATE TABLE IF NOT EXISTS genders (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL UNIQUE,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS faculties (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(150) NOT NULL UNIQUE,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;